---
cirrus-ci_task:
  container:
    image: toxchat/toktok-stack:0.0.15
    cpu: 2
    memory: 4G
  configure_script:
    - /src/workspace/tools/inject-repo hs-toxcore
  test_all_script:
    - bazel test -k
        --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST
        --config=release
        //hs-toxcore/...
