---
bazel-opt_task:
  container:
    image: toxchat/toktok-stack:latest-release
    cpu: 2
    memory: 6G
  configure_script:
    - /src/workspace/tools/inject-repo hs-toxcore
  test_all_script:
    - cd /src/workspace && bazel test -k
        --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST
        //hs-toxcore/...

android-aarch64_task:
  container:
    image: toktoknet/ghc-android:8.10.7.aarch64
    cpu: 2
    memory: 6G
  build_script:
    - android/build.sh

android-arm_task:
  container:
    image: toktoknet/ghc-android:8.10.7.arm
    cpu: 2
    memory: 6G
  build_script:
    - android/build.sh

android-i686_task:
  container:
    image: toktoknet/ghc-android:8.10.7.i686
    cpu: 2
    memory: 6G
  build_script:
    - android/build.sh

android-x86_64_task:
  container:
    image: toktoknet/ghc-android:8.10.7.x86_64
    cpu: 2
    memory: 6G
  build_script:
    - android/build.sh
