#!/bin/sh

curl --user ${CIRCLE_API_TOKEN}: \
  --data build_parameters[CIRCLE_JOB]=$1 \
  --data revision=$CIRCLE_SHA1 \
  https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH
