FROM toxchat/haskell:hs-toxcore AS build
FROM ubuntu:20.04

RUN apt-get update \
 && DEBIAN_FRONTEND="noninteractive" apt-get install -y --no-install-recommends \
 libsodium23 \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

COPY --from=build /bin/webservice /app/
CMD ["/app/webservice"]

# vim:ft=dockerfile
