#!/bin/sh

EXTRA_DIRS="--extra-include-dirs=$HOME/.cabal/extra-dist/include --extra-lib-dirs=$HOME/.cabal/extra-dist/lib"

# Install libsodium into $HOME/.cabal/extra-dist.
tools/install-libsodium
cabal install happy
cabal install --only-dependencies $EXTRA_DIRS
cabal install codecov-haskell hpc-coveralls aeson-0.9.0.1
cabal install stylish-haskell hlint
# cabal install pandoc
