#!/bin/sh

set -e -x

mkdir -p $HOME/.cabal/extra-dist

if test -f $HOME/.cabal/extra-dist/lib/libsodium.a; then exit; fi
if pkg-config libsodium; then exit; fi

cd test/toxcore/libsodium

git rev-parse HEAD > new-hash
if diff new-hash $HOME/.cabal/extra-dist/libsodium.hash; then
  rm new-hash
  exit
fi

echo "Hashes differ => rebuilding"
sh autogen.sh
./configure --prefix=$HOME/.cabal/extra-dist
make install

mv new-hash $HOME/.cabal/extra-dist/libsodium.hash
