#!/bin/sh

set -e -x

mkdir -p $HOME/.cabal/extra-dist

if test -f $HOME/.cabal/extra-dist/lib/libsodium.a; then exit; fi
if pkg-config libsodium; then exit; fi

git clone --depth=1 https://github.com/jedisct1/libsodium ../libsodium
cd ../libsodium

git rev-parse HEAD > new-hash
if diff new-hash $HOME/.cabal/extra-dist/libsodium.hash; then
  echo "libsodium is up-to-date"
  rm new-hash
else
  echo "Hashes differ => rebuilding"
  sh autogen.sh
  ./configure --prefix=$HOME/.cabal/extra-dist
  make install

  mv new-hash $HOME/.cabal/extra-dist/libsodium.hash
fi

cd -
