#!/usr/bin/env perl

use strict;

use IO::Socket::INET;

my $SUT = shift @ARGV or die "Usage: run-tests <server|toxcore> [args...]\n";
my $server = "dist/build/test-$SUT/test-$SUT";
die "$SUT is not a valid SUT. Choose one of [server, toxcore]\n" unless -f $server;

my $server_pid;
$SIG{INT} = sub { kill 2, $server_pid };
END { $server_pid and kill 15, $server_pid }
unless ($server_pid = fork) {
   exec "dist/build/test-$SUT/test-$SUT";
}

system "dist/build/test-tox/test-tox", @ARGV;
