#!/bin/sh

set -e

# sodium
cd test/toxcore/libsodium
sh autogen.sh
./configure --prefix=$PWD/_install
make install
mv _install/include/* /app/vendor/ghc-includes
mv _install/lib/* /app/vendor/ghc-libs
