# vim:ft=dockerfile
# https://github.com/iphydf/docker-build-ghc-android
FROM iphydf/haskell:8.0.1-@GHC_TARGET_ARCH@
MAINTAINER iphydf@gmail.com

WORKDIR $BASE

COPY user-scripts/build-libsodium.sh $BASE/
RUN ./build-libsodium.sh

#
# Install prerequisite haskell packages.
#
COPY patches/*.patch $BASE/patches/
COPY user-scripts/cabal-install-zlib.sh $BASE/
RUN ./cabal-install-zlib.sh

# distributive and comonad have a broken Setup.hs, so we need to configure with
# the host cabal and build with the target cabal.
COPY user-scripts/cabal-install-setup.sh $BASE/
RUN ./cabal-install-setup.sh distributive 0.5.0.2 \
 && ./cabal-install-setup.sh comonad 5

COPY user-scripts/install-deps.sh $BASE/
RUN ${NDK_TARGET}-cabal update \
 && ./install-deps.sh

WORKDIR $HOME

USER root
RUN apt-get install -y runit

ENTRYPOINT ["/home/androidbuilder/entrypoint.sh"]
WORKDIR /work
COPY user-scripts/entrypoint.sh /home/androidbuilder/
COPY user-scripts/target-cabal /home/androidbuilder/.cabal/bin/
